USE `SwitchBot`;

CREATE TABLE `Economy` (
        `client_id` VARCHAR(18) NOT NULL,
        `wallet` BIGINT(18) UNSIGNED NOT NULL,
        `bank` BIGINT(18) UNSIGNED NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;
